### ISSUE TITLE
ValueError during the "fab vagrant setup_vagrant" step

### ISSUE THREAD

**Issue by coeusthinks** [nsh87/shinyVM#10]
Hi there @nsh87,

Thanks for the guide. I'm coming across an issue with the "fab vagrant setup_vagrant" step. I've followed the guide as precisely as possible and have also uninstalled and reinstalled `paramiko` and `fabric`. However, installing the specific version of your `paramiko` did not successfully install. Some further information:

```
vagrant -v
Vagrant 1.9.5
python --version
Python 2.7
```

This is the error message that appears upon running `fab vagrant setup_vagrant`:
```
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\fabric\main.py", line 757, in main
    *args, **kwargs
  File "c:\python27\lib\site-packages\fabric\tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "c:\python27\lib\site-packages\fabric\tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "C:\shiny\fabfile.py", line 27, in vagrant
    if l])
ValueError: dictionary update sequence element #10 has length 0; 2 is required
```

Do you have any advice on how to resolve this error/issues?

Appreciate the help.

**Comment by mgerontini** [comment]
I had to change this line : **ssh_config = dict([l.strip().split() for l in raw_ssh_config.split("\n")**
to this :  ssh_config = dict([l.strip().split() for l in raw_ssh_config.decode(encoding='UTF-8').splitlines() if l])
The problem is with the encoding in python38 and the results gives two empty lines which cannot be parsed into a dictionary
