### ISSUE TITLE
ValueError: in step fab vagrant setup_vagrant

### ISSUE THREAD

**Issue by revorefurb** [nsh87/shinyVM#8]
Hello, I am able to get through vagrant up, but cannot complete the fab vagrant setup_vagrant. I'm quite stuck. Thanks for any help you can offer.

`fab vagrant setup_vagrant`

> Traceback (most recent call last):
>   File "c:\python27\lib\site-packages\fabric\main.py", line 756, in main
>     *args, **kwargs
>   File "c:\python27\lib\site-packages\fabric\tasks.py", line 427, in execute
>     results['<local-only>'] = task.run(*args, **new_kwargs)
>   File "c:\python27\lib\site-packages\fabric\tasks.py", line 174, in run
>     return self.wrapped(*args, **kwargs)
>   File "c:\Users\UID\OPIE\shinyVM\fabfile.py", line 27, in vagrant
>     if l])
> ValueError: dictionary update sequence element #10 has length 0; 2 is required
> 

I am running Windows 7 Enterprise SP1 64bit - Python 2.7.12 and the following versions of fabric packages:
`pip install --upgrade fabric`

> Requirement already up-to-date: fabric in c:\python27\lib\site-packages
> Requirement already up-to-date: paramiko<2.0,>=1.10 in c:\python27\lib\site-pack
> ages (from fabric)
> Requirement already up-to-date: pycrypto!=2.4,<3.0,>=2.1 in c:\python27\lib\site
> -packages\pycrypto-2.6.1-py2.7-win32.egg (from paramiko<2.0,>=1.10->fabric)
> Requirement already up-to-date: ecdsa<2.0,>=0.11 in c:\python27\lib\site-package
> s (from paramiko<2.0,>=1.10->fabric)

**Comment by abhivr** [comment]
Having the same error
